# Generated by Django 5.0.3 on 2024-03-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JpgToPdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jpg_file', models.ImageField(upload_to='jpg_conversions')),
                ('pdf_file', models.FileField(upload_to='pdf_conversions')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
